####play book start with 
---
- 
#this one dash is like an list of items in python
  #where you want to run the playbook
  hosts: ubuntu
  ####to define variables in ansible
  vars:
    tomcat_download_url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.72/bin/apache-tomcat-9.0.72.tar.gz
    tomcat_download_location: /usr/share/tomcat/apache-tomcat-9.0.72.tar.gz
  tasks:
    - name: install openjdk in ubuntu 
      ansible.builtin.package:
        name: default-jdk
        update_cache: yes
        state: present #absent
    - name: install unzip 
      ansible.builtin.package:
        name: unzip
    - name: create a tomcat group
      ansible.builtin.group:
        name: tomcat
        state: present
    - name: create a user tomcat 
      ansible.builtin.user:
        name: tomcat 
        #state: absent
        group: tomcat 
    - name: create a tomcat directory where i ll download the tomcat package 
      ansible.builtin.file:
        path: /usr/share/tomcat
        state: directory #file link absent
        owner: tomcat 
        group: tomcat 
    - name: Download the tomcat 
      ansible.builtin.get_url:
        url: "{{tomcat_download_url}}"
        dest: "{{tomcat_download_location}}"
    - name: unarchive the tomcat 
      ansible.builtin.unarchive:
        src: "{{tomcat_download_location}}"
        dest: /usr/share/tomcat
        owner: tomcat
        group: tomcat 
        remote_src: yes
        extra_opts: [--strip-components=1]
        creates: /usr/share/tomcat/bin
    - name: copy the tomcat service 
      copy:
        src: templates/tomcat.service.j2
        dest: /etc/systemd/system/tomcat.service
    - name:  start and enable tomcat 
      service:
        daemon_reload: yes
        name: tomcat 
        state: started 
        enable: yes 