####play book start with 
---
- 
#this one dash is like an list of items in python
  #where you want to run the playbook
  hosts: ubuntu
  ####to define variables in ansible
  vars:
    tomcat_download_url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.72/bin/apache-tomcat-9.0.72.tar.gz
    tomcat_download_location: /usr/share/tomcat/apache-tomcat-9.0.72
  tasks:
    - name: install openjdk in ubuntu 
      ansible.builtin.package:
        name: default-jdk
        update_cache: yes
        state: present #absent
    - name: create a tomcat group
      ansible.builtin.group:
        name: tomcat
        state: present
    - name: create a user tomcat 
      ansible.builtin.user:
        name: tomcat 
        group: tomcat 
    - name: create a tomcat directory where i ll download the tomcat package 
      ansible.builtin.file:
        path: /usr/share/tomcat
        state: directory #file link absent
        owner: tomcat 
        group: tomcat 
   
